// MACC_N_CHEESE Grammar 2016
// 
// Parser Class Definition File

// SHELL GENERATED BY PARSERGEN VERSION 5.0.3

#ifndef PARSER
#define PARSER

#include <string>
using namespace std;

#include "_____.h" // scanner class definition

#include "_____.h" // code generator class definition

class Parser
{
public:

	Parser();

	void SystemGoal();

private:

	Token savedToken;
	bool  tokenAvailable;

	void SyntaxError(Token t, string msg);

	Token NextToken();

	void Match(Token t);

	void InitTail();

	void VarDecTail();

	void VarDecList();

	void DecTail();

	void Declaration();

	void DecList();

	void BoolLit();

	void CheeseTypeTail();

	void CheeseType();

	void Type();

	void Literal();

	void MultOp();

	void FactorTail();

	void Primary();

	void AddOp();

	void ExprTail();

	void Factor();

	void RelOp();

	void CondTail();

	void IntListTail();

	void IntList();

	void CaseListTail();

	void Case();

	void CaseList();

	void ForAssign();

	void ElseClause();

	void Condition();

	void VarDecs();

	void SelectStmt();

	void ForStmt();

	void WhileStmt();

	void LoopStmt();

	void IfStmt();

	void ItemListTail();

	void ItemList();

	void VariableTail();

	void VarListTail();

	void VarList();

	void InitList();

	void Expression();

	void AssignTail();

	void Variable();

	void BreakStmt();

	void ShoutStmt();

	void ListenStmt();

	void AssignStmt();

	void StructStmt();

	void SimpleStmt();

	void StmtTail();

	void Statement();

	void StmtList();

	void Program();

}; // end of Parser class

#endif
