LDA       R15,VARS
LDA       R14,STRS
LDA       R13,BOOL
STO       R0,"perfect"
JMP        &8
STO       R0,"perfect"
JMP        &8
STO       R0,"perfect"
JMP        &8
STO       R0,"perfect"
JMP        &8
STO       R0,"perfect"
JMP        &8
STO       R0,"perfect"
JMP        &8
LD        R0,+0(R15)
STO       R0,"perfect"
JMP        &7
STO       R0,"perfect"
JMP        &8
STO       R0,"permanent"
JMP        &10
STO       R0,"permanent"
JMP        &10
STO       R0,"permanent"
JMP        &10
STO       R0,"permanent"
JMP        &10
STO       R0,"permanent"
JMP        &10
STO       R0,"permanent"
JMP        &10
STO       R0,"permanent"
JMP        &10
STO       R0,"permanent"
JMP        &10
LD        R0,+1024(R15)
STO       R0,"permanent"
JMP        &9
STO       R0,"permanent"
JMP        &10
WRST       +0(R14)
WRNL      
WRST       +10(R14)
WRNL      
